version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD:-postgres}
      POSTGRES_DB: ${PSQL_DATABASE:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PSQL_PORT:-5432}:5432"
    networks:
      - infrastructure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USERNAME:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: ["redis-server"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    networks:
      - infrastructure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

volumes:
  pgdata:
  redisdata:

networks:
  infrastructure:
